### PR TITLE
add a dockerfile to run this in a container as well

### PR DESCRIPTION
**Pull request by davidgibbons**
Just added a basic dockerfile so I can use this in swarm easier.

### CODE REVIEW

**Comment by deltaskelta** [comment]
Can you explain how you are using this?

1. I am a little bit confused because I can't see the command you use to run the container. the unix socket must be mounted, right?

2. How are you handling the configuration when you run it with the dockerfile? 

3. I am getting a failure when I build and run the container because `docker-alertd` is no longer the name of the binary, it is `app` within the container because it was built in the `app` folder of `$GOPATH/src`

**Comment by davidgibbons** [comment]
Sure no problem, and i'll admit I'm still exploring how i'll use it. 

Yeah I use docker-compose/stacks and swarm in my infrastructure: I'm looking at laying out a configuration yaml file on the host via config management and then bind mounting it into the container along with the socket file, this is similar to how we use portainer/traefik.
So something like this:
```
version: '3.1'
services:
  alertd:
    image: internal.registry/docker-alertd
    deploy:
      mode: global
      restart_policy:
        condition: any
        delay: 5s
        window: 120s
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/docker-alertd.yml:/root/.docker-alertd.yml
```

This can be manually tested with something like:
`docker run -v /var/run/docker.sock:/var/run/docker.sock -v /etc/docker-alertd.yml:/root/.docker-alertd.yml docker-registry.internal/docker-alertd:latest`

**Comment by davidgibbons** [comment]
Oh and I had originally had just run app in the dockerfile but was poking around with changing it, didn't mean to commit that though, just run app.

**Comment by deltaskelta** [comment]
Thanks for your input, I have made issue #22 out of this because I want to add some stuff along with the dockerfile and then I will merge it. Thanks

**Pull request merged**
